# Generated by Django 4.2.21 on 2025-07-23 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('imagen_satelital', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('cantidadLotes', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
