# Generated by Django 5.2 on 2025-05-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('cantidad_lotes', models.IntegerField()),
                ('imagen_satelital', models.ImageField(blank=True, null=True, upload_to='imagenes_campos/')),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
