# Generated by Django 5.2 on 2025-05-02 16:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='cantidad_lotes',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='provincia',
        ),
        migrations.AddField(
            model_name='campo',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='campo',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='campo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
