# Generated by Django 4.2.20 on 2025-05-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campo",
            name="localidad",
            field=models.CharField(default="Sin especificar", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campo",
            name="provincia",
            field=models.CharField(default="Sin especificar", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campo",
            name="imagen_satelital",
            field=models.ImageField(blank=True, null=True, upload_to="imagenes/"),
        ),
    ]
