# Generated by Django 4.2.20 on 2025-11-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0002_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
