# Generated by Django 4.2.21 on 2025-07-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0002_campo_localidad_campo_provincia_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='campo',
            name='cantidadLotes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
