# Generated by Django 4.2.20 on 2025-05-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0002_campo_localidad_campo_provincia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='campo',
            name='cantidadLotes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
