# Generated by Django 4.2.20 on 2025-11-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0003_campo_latitud_campo_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='longitud',
        ),
        migrations.AlterField(
            model_name='campo',
            name='cantidadLotes',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
