# Generated by Django 4.2.20 on 2025-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0003_remove_campo_ubicacion_campo_cantidadlotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='localidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='campo',
            name='provincia',
            field=models.CharField(max_length=100),
        ),
    ]
