# Generated by Django 4.2.20 on 2025-12-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0004_remove_campo_latitud_remove_campo_longitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='cantidadLotes',
        ),
    ]
