# Generated by Django 4.2.20 on 2025-05-04 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lotes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("siembra", "Siembra"),
                            ("aplicacion", "Aplicación"),
                            ("riego", "Riego"),
                            ("cosecha", "Cosecha"),
                            ("fertilizacion", "Fertilización"),
                            ("otra", "Otra"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("fecha", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("completada", "Completada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="lotes.lote",
                    ),
                ),
            ],
        ),
    ]
