# Generated by Django 4.2.20 on 2025-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_rename_descripcion_tarea_observaciones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='observaciones',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='concentracion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='de',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='dosis_tipo',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fabricante',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='hectareas_aplicadas',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='litros_por_ha',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='lkg_por_ha',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='mapa_adjunto',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='mapa_variable',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='operario',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='plaga_maleza',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='producto_aplicar',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='tipo_fertilizante',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='tipo_fitosanitario',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='tipo_laboreo',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='tipo_riego',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='volumen',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('siembra', 'Siembra'), ('aplicacion', 'Aplicación'), ('riego', 'Riego'), ('cosecha', 'Cosecha'), ('fertilizacion', 'Fertilización'), ('otra', 'Otra')], max_length=30),
        ),
    ]
