# Generated by Django 4.2.20 on 2025-08-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_rename_observaciones_tarea_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='descripcion',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='estado',
        ),
        migrations.AddField(
            model_name='tarea',
            name='concentracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='dosis_tipo',
            field=models.CharField(blank=True, choices=[('fija', 'Fija'), ('variable', 'Variable'), ('', 'No aplica')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fabricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='hectareas_aplicadas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='litros_por_ha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='lkg_por_ha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='mapa_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='mapas_fertilizacion/'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='mapa_variable',
            field=models.FileField(blank=True, null=True, upload_to='mapas_maleza/'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='operario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='plaga_maleza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='producto_aplicar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipo_fertilizante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipo_fitosanitario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipo_laboreo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipo_riego',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='volumen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('fertilizacion', 'Fertilización'), ('maleza', 'Manejo de Malezas'), ('laboreo', 'Laboreos de Lote'), ('riego', 'Riego'), ('fitosanitaria', 'Aplicación Fitosanitaria'), ('otra', 'Otra')], max_length=30),
        ),
    ]
