# Generated by Django 4.2.20 on 2025-09-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_rename_descripcion_tarea_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-fecha', '-creado_en']},
        ),
        migrations.AddField(
            model_name='tarea',
            name='actividad_libre',
            field=models.CharField(blank=True, help_text="Título o breve descripción cuando tipo = 'Otros'", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tipo',
            field=models.CharField(choices=[('fertilizacion', 'Fertilización'), ('maleza', 'Manejo de Malezas'), ('laboreo', 'Laboreos de Lote'), ('riego', 'Riego'), ('fitosanitaria', 'Aplicación Fitosanitaria'), ('otros', 'Otros')], max_length=30),
        ),
    ]
