# Generated by Django 4.2.21 on 2025-07-23 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_pdf', models.FileField(upload_to='reportes/')),
                ('fecha_reporte', models.DateTimeField()),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos.campo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lote')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
