# Generated by Django 4.2.20 on 2025-08-30 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('y_pct', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('texto', models.CharField(max_length=200)),
                ('color', models.CharField(default='#e74c3c', max_length=7)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anotaciones', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='reportes.reporte')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'indexes': [models.Index(fields=['reporte', 'creado_en'], name='reportes_an_reporte_088e14_idx')],
            },
        ),
    ]
