# Generated by Django 4.2.20 on 2025-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_anotacion_drop_reporte'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='anotacion',
            name='reportes_an_reporte_088e14_idx',
        ),
        migrations.AddIndex(
            model_name='anotacion',
            index=models.Index(fields=['lote', 'creado_en'], name='reportes_an_lote_id_9689e6_idx'),
        ),
    ]
