# Generated by Django 4.2.20 on 2025-12-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_remove_anotacion_reportes_an_reporte_088e14_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='fecha_reporte',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
