# Generated by Django 4.2.21 on 2025-07-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.FloatField(help_text='Área del lote en hectáreas')),
                ('observacion', models.TextField(blank=True)),
                ('coordenadas', models.JSONField(blank=True, null=True)),
                ('imagen_satelital', models.ImageField(blank=True, null=True, upload_to='imagenes/lotes/')),
                ('imagen_dron', models.ImageField(blank=True, null=True, upload_to='imagenes/drones/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='campos.campo')),
            ],
        ),
    ]
