# Generated by Django 5.2 on 2025-05-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='propietario',
        ),
    ]
