# Generated by Django 4.2.21 on 2025-08-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Siembra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("cultivo", models.CharField(max_length=100)),
                ("variedad", models.CharField(max_length=100)),
                ("densidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unidad_densidad",
                    models.CharField(
                        choices=[("Kg/Ha", "Kg/Ha"), ("Pl/Ha", "Pl/Ha")], max_length=10
                    ),
                ),
                ("ventana_cosecha", models.DateField()),
                (
                    "analisis_suelo",
                    models.FileField(
                        blank=True, null=True, upload_to="siembra/analisis/"
                    ),
                ),
                (
                    "lote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siembra",
                        to="lotes.lote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cosecha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("rinde", models.CharField(max_length=100)),
                (
                    "archivo_rendimiento",
                    models.FileField(blank=True, null=True, upload_to="cosechas/"),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lotes.lote"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cobertura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("cultivo", models.CharField(max_length=100)),
                ("variedad", models.CharField(max_length=100)),
                ("densidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "lote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cobertura",
                        to="lotes.lote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campania",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_siembra", models.DateField()),
                ("cultivo", models.CharField(max_length=100)),
                ("variedad", models.CharField(max_length=100)),
                ("densidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unidad_densidad",
                    models.CharField(
                        choices=[("Kg/Ha", "Kg/Ha"), ("Pl/Ha", "Pl/Ha")], max_length=10
                    ),
                ),
                ("ventana_cosecha", models.DateField()),
                (
                    "analisis_suelo",
                    models.FileField(
                        blank=True, null=True, upload_to="campanias/siembra/"
                    ),
                ),
                ("fecha_cosecha", models.DateField(blank=True, null=True)),
                ("rinde", models.CharField(blank=True, max_length=100)),
                (
                    "archivo_rendimiento",
                    models.FileField(
                        blank=True, null=True, upload_to="campanias/cosechas/"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campanias",
                        to="lotes.lote",
                    ),
                ),
            ],
        ),
    ]
