# Generated by Django 4.2.20 on 2025-06-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='coordenadas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='observacion',
            field=models.TextField(blank=True),
        ),
    ]
