# Generated by Django 4.2.21 on 2025-09-06 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0002_siembra_cosecha_cobertura_campania"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoLote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SIEMBRA", "Siembra"),
                            ("COSECHA", "Cosecha"),
                            ("FERTILIZACION", "Fertilización"),
                            ("MALEZAS", "Manejo de Malezas"),
                            ("LABOREO", "Laboreo"),
                            ("RIEGO", "Riego"),
                            ("FITOSANITARIA", "Aplicación Fitosanitaria"),
                            ("OTRA", "Otra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "db_table": "lotes_eventolote",
                "ordering": ["fecha", "id"],
                "indexes": [
                    models.Index(
                        fields=["lote", "fecha"], name="lotes_event_lote_id_b78f59_idx"
                    )
                ],
            },
        ),
    ]
