# Generated by Django 4.2.21 on 2025-07-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_lote_coordenadas_lote_observacion_siembra_cosecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobertura',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='cosecha',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='siembra',
            name='lote',
        ),
        migrations.DeleteModel(
            name='Campania',
        ),
        migrations.DeleteModel(
            name='Cobertura',
        ),
        migrations.DeleteModel(
            name='Cosecha',
        ),
        migrations.DeleteModel(
            name='Siembra',
        ),
    ]
