# Generated by Django 4.2.21 on 2025-09-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0003_eventolote"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventoLote",
        ),
    ]
