# Generated by Django 4.2.20 on 2025-11-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_delete_eventolote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('barbecho', 'Barbecho'), ('sembrado', 'Sembrado'), ('cosechado', 'Cosechado'), ('con_cobertura', 'Con Cobertura')], default='barbecho', max_length=20),
        ),
    ]
