# Generated by Django 4.2.20 on 2025-11-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0005_lote_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='estado',
        ),
    ]
