# Generated by Django 4.2.20 on 2025-11-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0006_remove_lote_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobertura',
            old_name='fecha',
            new_name='fecha_cobertura',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='imagen_dron',
            new_name='imagen_drone',
        ),
        migrations.AddField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('barbecho', 'Barbecho'), ('sembrado', 'Sembrado'), ('cosechado', 'Cosechado'), ('cosechado', 'Cosechado')], default='barbecho', max_length=20),
        ),
    ]
