# Generated by Django 4.2.20 on 2025-11-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0007_rename_fecha_cobertura_fecha_cobertura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cobertura',
            old_name='fecha_cobertura',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='imagen_drone',
            new_name='imagen_dron',
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('barbecho', 'Barbecho'), ('sembrado', 'Sembrado'), ('cosechado', 'Cosechado'), ('cobertura', 'Cobertura')], default='barbecho', max_length=20),
        ),
    ]
