# Generated by Django 4.2.20 on 2025-11-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0008_rename_fecha_cobertura_cobertura_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campania',
            name='cultivo_cobertura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campania',
            name='densidad_cobertura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campania',
            name='fecha_cobertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campania',
            name='variedad_cobertura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
