# Generated by Django 4.2.20 on 2025-11-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0009_campania_cultivo_cobertura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temp_baja', 'Temperatura muy baja'), ('temp_alta', 'Temperatura muy alta'), ('granizo', 'Probabilidad de granizo'), ('incendio', 'Riesgo de incendio'), ('tormenta_severa', 'Tormenta severa')], max_length=50)),
                ('mensaje', models.TextField()),
                ('valor_detectado', models.FloatField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('info', 'Informativa'), ('moderada', 'Moderada'), ('alta', 'Alta'), ('critica', 'Crítica')], default='info', max_length=20)),
                ('fuente', models.CharField(default='openweather', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vista', models.BooleanField(default=False)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='lotes.lote')),
            ],
        ),
    ]
