# Generated by Django 4.2.20 on 2025-08-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('cultivo', models.CharField(blank=True, max_length=100, null=True)),
                ('variedad', models.CharField(blank=True, max_length=100, null=True)),
                ('dias_madurez', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
