# Generated by Django 4.2.21 on 2025-08-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="precio",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="stock",
        ),
        migrations.AddField(
            model_name="producto",
            name="cultivo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="dias_madurez",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="tipo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="variedad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
