# Generated by Django 4.2.20 on 2025-06-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_precio_remove_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cultivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='dias_madurez',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='variedad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
