# Generated by Django 4.2.20 on 2025-06-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_cultivo_producto_dias_madurez_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
