# Generated by Django 4.2.20 on 2025-06-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
