# Generated by Django 4.2.20 on 2025-11-24 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_imagen_perfil_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_alta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
