# Generated by Django 4.2.20 on 2025-05-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_rol_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(default='imagenes/user.jpg', upload_to='perfiles/'),
        ),
    ]
